apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wil-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/XanaCo/ancolmen-IoT
    targetRevision: IoT_an
    path: p3/dev/
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true