apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-project
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/XanaCo/ancolmen-IoT
    targetRevision: IoT_an
    path: p3/confs/dev/
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wil-playground
  namespace: dev
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: wil-service
            port:
              number: 8888