# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
	config.vm.box = "debian/bookworm64"

	# Define 1st VM
	config.vm.define "cbernazeS" do |server|
		server.vm.hostname = "cbernazeS"
		server.vm.network "private_network", ip: "192.168.56.110"
		server.vm.provider "virtualbox" do |vb|
			vb.customize ["modifyvm", :id, "--name", "cbernazeS"]
			vb.memory = "1024"
			vb.cpus = 1
		end
		server.vm.provision "shell", inline: <<-SCRIPT
			sh /vagrant/scripts/k3s_server.sh
		SCRIPT
	end

	# Define 2nd VM
	config.vm.define "cbernazeSW" do |worker|
		worker.vm.hostname = "cbernazeSW"
		worker.vm.network "private_network", ip: "192.168.56.111"
		worker.vm.provider "virtualbox" do |vb|
			vb.customize ["modifyvm", :id, "--name", "cbernazeSW"]
			vb.memory = "1024"
			vb.cpus = 1
		end
		worker.vm.provision "shell", inline: <<-SCRIPT
			sh /vagrant/scripts/k3s_agent.sh
		SCRIPT
	end
end