# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

SERVER = "cbernazeS"
WORKER = "cbernazeSW"
IP_SERVER = "192.168.56.110"
IP_WORKER = "192.168.56.111"
VM_RAM_MB = "1024"
VM_CPU_NBR = 1

Vagrant.configure("2") do |config|
	config.vm.box = "debian/bookworm64"

	# Define server VM
	config.vm.define SERVER do |server|
		server.vm.hostname = SERVER
		server.vm.network "private_network", ip: IP_SERVER
		server.vm.provider "virtualbox" do |vb|
			vb.customize ["modifyvm", :id, "--name", SERVER]
			vb.memory = VM_RAM_MB
			vb.cpus = VM_CPU_NBR
		end
		server.vm.provision "shell", inline: <<-SCRIPT
			sh /vagrant/scripts/k3s_server.sh
		SCRIPT
	end

	# Define worker VM
	config.vm.define WORKER do |worker|
		worker.vm.hostname = WORKER
		worker.vm.network "private_network", ip: IP_WORKER
		worker.vm.provider "virtualbox" do |vb|
			vb.customize ["modifyvm", :id, "--name", WORKER]
			vb.memory = VM_RAM_MB
			vb.cpus = VM_CPU_NBR
		end
		worker.vm.provision "shell", inline: <<-SCRIPT
			sh /vagrant/scripts/k3s_agent.sh
		SCRIPT
	end
end