# App 3
apiVersion: v1
kind: ConfigMap
metadata:
  name: app3-html
data:
  index.html: app3.html

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-three
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: app-three
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
          - containerPort: 80
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: app3-volume
      volumes:
      - name: app3-volume
        configMap:
          name: app3-hmtl

---
apiVersion: v1
kind: Service
metadata:
	name: app-three
spec:
	# type: ClusterIP
	selector:
		app: app-three
	ports:
		-	protocol: TCP
			port: 80
			# targetPort: 8080 No need to add the targetPort as kubernetes assumes it is the same as the exposed port above
	# clusterIP: 10.43.171.213

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-one-ingress
spec:
  rules:
  - host: app1.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: app-one-service
            port:
              number: 80